
package com.htichina.wsclient.payment;

import com.htichina.common.web.ConfigureInfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentServiceService", targetNamespace = "http://payment.ws.htichina.com/", wsdlLocation = "http://10.198.50.233:8080/b2c_portal/ws/paymentService?wsdl")
public class PaymentServiceService
    extends Service
{

    private final static URL PAYMENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSERVICESERVICE_EXCEPTION;
    private final static QName PAYMENTSERVICESERVICE_QNAME = new QName("http://payment.ws.htichina.com/", "PaymentServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(ConfigureInfo.getB2CPaymentServiceEndPoint());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSERVICESERVICE_WSDL_LOCATION = url;
        PAYMENTSERVICESERVICE_EXCEPTION = e;
    }

    public PaymentServiceService() {
        super(__getWsdlLocation(), PAYMENTSERVICESERVICE_QNAME);
    }

    public PaymentServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSERVICESERVICE_QNAME, features);
    }

    public PaymentServiceService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSERVICESERVICE_QNAME);
    }

    public PaymentServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSERVICESERVICE_QNAME, features);
    }

    public PaymentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServicePort")
    public PaymentService getPaymentServicePort() {
        return super.getPort(new QName("http://payment.ws.htichina.com/", "PaymentServicePort"), PaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServicePort")
    public PaymentService getPaymentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://payment.ws.htichina.com/", "PaymentServicePort"), PaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSERVICESERVICE_EXCEPTION!= null) {
            throw PAYMENTSERVICESERVICE_EXCEPTION;
        }
        return PAYMENTSERVICESERVICE_WSDL_LOCATION;
    }

}
